
drop database IF EXISTS ${jdbc.test.databaseName};

create database ${jdbc.test.databaseName};
use ${jdbc.test.databaseName};

-- -----------------------------------------------------
-- Table `n2a`.`TRANSACTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TRANSACTION` ;

CREATE  TABLE IF NOT EXISTS `TRANSACTION` (
  `TRANSACTION_ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `TRANSACTION_TYPE_ID` BIGINT(20) UNSIGNED NOT NULL ,
  `OPERATOR_ID` INT(11) UNSIGNED NOT NULL ,
  `WORKSTATION_ID` INT(11) UNSIGNED NOT NULL ,
  `BEGIN_DATE` DATETIME NOT NULL ,
  `END_DATE` DATETIME NULL ,
  PRIMARY KEY (`TRANSACTION_ID`) ,
  INDEX `fk_TRANSACTION_OPERATOR` (`OPERATOR_ID` ASC) ,
  INDEX `fk_TRANSACTION_WORKSTATION` (`WORKSTATION_ID` ASC) ,
  INDEX `fk_TRANSACTION_TRANSACTION_TYPE` (`TRANSACTION_TYPE_ID` ASC) ,
  UNIQUE INDEX `UNIQUE_TRANSACTION_ID_TRANSACTION_TYPE_ID` (`TRANSACTION_ID` ASC, `TRANSACTION_TYPE_ID` ASC)
  );
  
INSERT INTO TRANSACTION (TRANSACTION_ID, TRANSACTION_TYPE_ID,OPERATOR_ID,
  WORKSTATION_ID , BEGIN_DATE, END_DATE) VALUES (2,1,1,1,'2009-09-22','2009-09-22');