package com.djimenez.core.patterns.impl.mediator;

import org.apache.log4j.Logger;

import com.djimenez.core.patterns.impl.observer.AbstractNotifier;
import com.djimenez.core.patterns.interfaces.Facade;
import com.djimenez.core.patterns.interfaces.mvc.Mediator;

public abstract class AbstractMediator extends AbstractNotifier implements
  Mediator {

  protected static final Logger logger =
    Logger.getLogger(AbstractMediator.class);

  private Facade facade;

  private String mediatorName = null;

  private Object viewComponent = null;

  protected AbstractMediator() {

    this.mediatorName = this.getClass().getName();
    if (logger.isDebugEnabled()) {
      logger.debug("Initialized Mediator " + this.mediatorName);
    }
  }

  protected AbstractMediator(final Object viewComponent) {
    this();
    this.viewComponent = viewComponent;
    if (logger.isDebugEnabled()) {
      logger.debug("Initialized viewComponent " + this.viewComponent + " @ "
        + this.mediatorName);
    }
  }

  /**
   * @param mediatorName
   *          Try to use autogenerated mediator naming
   */
  protected AbstractMediator(final String mediatorName) {
    this(mediatorName, null);
  }

  /**
   * @param mediatorName
   * @param viewComponent
   *          Try to use autogenerated mediator naming
   */
  protected AbstractMediator(final String mediatorName,
    final Object viewComponent) {

    this.mediatorName = mediatorName;
    this.viewComponent = viewComponent;
    if (logger.isDebugEnabled()) {
      logger.debug("Initialized Mediator " + mediatorName + " for View "
        + viewComponent);
    }
  }

  @Override
  public void assignFacade(final Facade activefacade) {

    this.facade = activefacade;
  }

  @Override
  public Facade getFacade() {
    return facade;
  }

  @Override
  public final String getMediatorName() {
    return this.mediatorName;
  }

  @Override
  public Object getViewComponent() {
    return this.viewComponent;
  }

  @Override
  public void setFacade(final Facade facade) {
    this.facade = facade;
  }

  @Override
  public void setViewComponent(final Object viewComponent) {
    this.viewComponent = viewComponent;
  }

}
